name: flutter_api_list
description: A Flutter project that fetches and displays a list from an API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4 # Dùng để gọi API
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  floor: ^1.4.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.4.6
flutter:
  uses-material-design: true

  assets:
    - assets/images/image.png
    - assets/images/logo.png