// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Ss-gbDb8OcidT-IKpX3xNn8qxDts5Dw',
    appId: '1:400326450130:web:a7a10e2321d95d5c08860b',
    messagingSenderId: '400326450130',
    projectId: 'bai1-e1bf7',
    authDomain: 'bai1-e1bf7.firebaseapp.com',
    storageBucket: 'bai1-e1bf7.firebasestorage.app',
    measurementId: 'G-ZGJXF7V4DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIkNqgh2p78egFFM4I3AWvS7qZP_74c1I',
    appId: '1:400326450130:android:75bb4de35bd0b12b08860b',
    messagingSenderId: '400326450130',
    projectId: 'bai1-e1bf7',
    storageBucket: 'bai1-e1bf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCom4LGdugBA5-IIpEZAMdvHxxV1MXjp1w',
    appId: '1:400326450130:ios:a6e0296e603f312508860b',
    messagingSenderId: '400326450130',
    projectId: 'bai1-e1bf7',
    storageBucket: 'bai1-e1bf7.firebasestorage.app',
    iosBundleId: 'com.example.tuan3Bai2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCom4LGdugBA5-IIpEZAMdvHxxV1MXjp1w',
    appId: '1:400326450130:ios:a6e0296e603f312508860b',
    messagingSenderId: '400326450130',
    projectId: 'bai1-e1bf7',
    storageBucket: 'bai1-e1bf7.firebasestorage.app',
    iosBundleId: 'com.example.tuan3Bai2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Ss-gbDb8OcidT-IKpX3xNn8qxDts5Dw',
    appId: '1:400326450130:web:d2d99baa581830b308860b',
    messagingSenderId: '400326450130',
    projectId: 'bai1-e1bf7',
    authDomain: 'bai1-e1bf7.firebaseapp.com',
    storageBucket: 'bai1-e1bf7.firebasestorage.app',
    measurementId: 'G-MN6PTKYKW4',
  );
}
